### ISSUE TITLE
Enclave Trust is NOT TRUSTED and COMPLICATED. The client is out of date.

### ISSUE THREAD

**Issue by anand10717** [intel/sgx-ra-sample#29]
Iam using DELL latitue E7470 with following configuration,
Processor :  intel Core i7 6th gen
OS : Ubuntu 16.04
BIOS version : 1.21.6 (latest version released on june 3rd)

I have updated my BIOS to its available latest version still im getting  **Enclave Trust is NOT TRUSTED and COMPLICATED** as IAS report attestation result.

BIOS version : 

> sudo dmidecode
dmidecode 3.0
Getting SMBIOS data from sysfs.
SMBIOS 3.0 present.
107 structures occupying 6184 bytes.
Table at 0x000EA8E0.
Handle 0x0000, DMI type 0, 24 bytes
BIOS Information
	Vendor: Dell Inc.
	Version: 1.21.6
	Release Date: 05/20/2019
	Address: 0xF0000
	Runtime Size: 64 kB
	ROM Size: 16384 kB
	Characteristics:

SGX Remote Attestation IAS result :+1: 

> ---- Enclave Trust Status from Service Provider ----------------------------
Enclave Trust is NOT TRUSTED and COMPLICATED. The client is out of date.-------------------------------------------------------------------------------- Platform Update Required ----------------------------------------------
The following Platform Update(s) are required to bring this
platform's Trusted Computing Base (TCB) back into compliance:
The CPU Microcode needs to be updated.  Contact your OEM for a platform BIOS Update.

Please let me know the possible solutions!

Thank you!

**Comment by anand10717** [comment]
releated thread in intel forum :
https://software.intel.com/en-us/forums/intel-software-guard-extensions-intel-sgx/topic/815891

**Comment by jmechalas** [comment]
We are looking into this. One of the possibilities is that microcode patches were released after Dell's BIOS validation cycle had finished, which means another BIOS update is probably in the works. But we won't know for sure until we analyze the list of SA's. It's also possible there's an error on our end.

**Comment by dtzimmerman** [comment]
Hi,

In your 'settings' file, set VERBOSE=1

If you re-run/restart the server (./run-server), you should see additional output in the form of:

---- IAS Advisories --------------------------------------------------------
https://security-center.intel.com

INTEL-SA-00233

----------------------------------------------------------------------------

The output above is from my Dell 3510 (i7-6820HQ).  The server side output is telling me the client is out of date, and its due to Intel Security Advisory INTEL-SA-00233.  Depending on how are out of date your platform is, you may see additional Security Advisory IDs.

For my particular platform, there is a BIOS update available containing the required patch for INTEL-SA-00233 which should bring the system back into compliance once the update is applied.

Your platform may not yet have a BIOS update to resolves / mitigates INTEL-SA-00233.  In this case, contact your OEM / Platform Vendor Support Team.

**Comment by johnmajewski** [comment]
I see no advisories on my end, but continue to receive the "Enclave Trust is NOT TRUSTED and COMPLICATED" error.  This is that start of my server log:

Server log started
Aug 19 2019 20:54:00 +++ IAS Primary Subscription Key set to 'b5cf........................1515'
Aug 19 2019 20:54:00 +++ IAS Secondary Subscription Key set to 'b931........................5cd4'
Aug 19 2019 20:54:00 +++ Using default CA bundle C:\Program Files\cURL\bin\curl-ca-bundle.crt
Aug 19 2019 20:54:00 Using default private key
Aug 19 2019 20:54:00 +++ using private key:
Aug 19 2019 20:54:00 Listening for connections on port 7777


Thanks

**Comment by anand10717** [comment]
> Iam using DELL latitue E7470 with following configuration,
Processor : intel Core i7 6th gen
OS : Ubuntu 16.04
BIOS version : 1.21.6 (latest version released on june 3rd)

In my case! i am getting advisory-id : INTEL-SA-00233 in IAS response.
BIOS update for the same vulnerability is scheduled to release on Aug 2019. So Everyone may get BIOS updates for their respective machines soon which will solve this issue.
