### ISSUE TITLE
ra sample using the SDK 2.5+ quote functions

### ISSUE THREAD

**Issue by tomtau** [intel/sgx-ra-sample#40]
Since SDK 2.5, there are a few functions that, according to the reference manual, should be able to do ECDSA- and EPID-based attestation -- `sgx_select_att_key_id`, `sgx_init_quote_ex`, `sgx_get_quote_size_ex`, and `sgx_get_quote_ex`.

 I'm puzzled how to use them -- e.g. where to get `p_att_key_id_list` ("List of the supported attestation key IDs provided by the quote verifier") if one tries to use them with IAS EPID (is it ok to just pass a null pointer?).
Could readme link some example that shows how to use them for reference or could this sample be adapted (e.g. on a different branch) to use these functions?

**Comment by tomtau** [comment]
There's a sample code in SDK's repo, but it doesn't help much, as these values are hardcoded without any explanation how they can be obtained: https://github.com/intel/linux-sgx/blob/master/SampleCode/RemoteAttestation/service_provider/service_provider.cpp#L125

**Comment by mechalas** [comment]
We're planning a new sample that will support ECDSA attestation but don't have a timeline at the moment.

**Comment by GuilhemN** [comment]
In case this helps, I've been working on an adaptation supporting ECDSA attestation: https://github.com/labri-progress/SGX-DCAP-Quote-Generation-Dockerfile/tree/7360521e5f98487f77be1812b937e388aadc7880/RemoteAttestation.
That's not mergeable as is since I did not need it to be as flexible as the original version but it may give an idea of the changes required to support SGX DCAP.

**Comment by jmechalas** [comment]
Thanks for the pointer. I will take a look at your approach.

I am going to close this out because the inquiry is out of scope for the code sample.
